version: '3.0'

services:
    web:
        container_name: php-apache
        build: .
        depends_on:
            - mysql
        volumes:
            - ./app:/var/www/html/
        ports:
            - 80:80
   
    phpmyadmin:
        container_name: php-admin
        image: phpmyadmin
        ports:
            -  82:80
        restart: always
        environment:
            PMA_HOST: mysql
        depends_on:
            - mysql

    mysql:
        container_name: mysql-db
        image: mysql
        restart: always
        volumes:
            - dbdata:/var/lib/mysql
            - ./db:/docker-entrypoint-initdb.d/
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: crud
        ports:
          - 3306:3306
volumes:
  dbdata: